// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ScanOptions(arg1) {
  return window['go']['main']['App']['ScanOptions'](arg1);
}
