// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSystemHealth():Promise<main.SystemHealth>;

export function Greet(arg1:string):Promise<string>;

export function ScanOptions(arg1:main.ScanRequest):Promise<main.ScanResponse>;
